In [1]:
from sentence_transformers import CrossEncoder

In [2]:
model = CrossEncoder('vectara/hallucination_evaluation_model')

In [3]:
model 

In [4]:
scores = model.predict([
    ["A man walks into a bar and buys a drink", "A bloke swigs alcohol at a pub"],
    ["A person on a horse jumps over a broken down airplane.", "A person is at a diner, ordering an omelette."],
    ["A person on a horse jumps over a broken down airplane.", "A person is outdoors, on a horse."],
    ["A boy is jumping on skateboard in the middle of a red bridge.", "The boy skates down the sidewalk on a blue bridge"],
    ["A man with blond-hair, and a brown shirt drinking out of a public water fountain.", "A blond drinking water in public."],
    ["A man with blond-hair, and a brown shirt drinking out of a public water fountain.", "A blond man wearing a brown shirt is reading a book."],
    ["Mark Wahlberg was a fan of Manny.", "Manny was a fan of Mark Wahlberg."],  
])

In [5]:
scores

array([6.1051559e-01, 4.7493738e-04, 9.9639291e-01, 2.1221573e-04,
       9.9599433e-01, 1.4126955e-03, 2.8262965e-03], dtype=float32)

In [8]:
import numpy as np 

In [9]:
# Convert the values to one decimal point
score_one_decimal = np.around(scores, decimals=1)

In [10]:
# Convert the values to percentage with one decimal point
score_percentage = np.around(scores * 100, decimals=1)


In [11]:
score_one_decimal

array([0.6, 0. , 1. , 0. , 1. , 0. , 0. ], dtype=float32)

In [12]:
score_percentage

array([61.1,  0. , 99.6,  0. , 99.6,  0.1,  0.3], dtype=float32)